;  See https://tox.wiki/en/stable/
[tox]
requires =
    tox>=4
    tox-uv
envlist =
    py3{10,11,12,13,14}-{plotting,flaky}
skip_missing_interpreters = true


; ENVIRONMENTS
; ------------
[min_python]
description = minimum python version
skip_install = false
base_python = 3.10


[global_var]
passenv =
    CI
    USERNAME
    # Pass user color preferences through
    PY_COLORS
    FORCE_COLOR
    NO_COLOR
    CLICOLOR
    CLICOLOR_FORCE


; COMMANDS
; --------
[testenv:doc]
description = Build doc with minimum supported version of python and all dependencies (plotting included).
base_python = {[min_python]base_python}
passenv =
    {[global_var]passenv}
    PATTERN
extras =
    doc
uv_resolution = lowest-direct
allowlist_externals =
    make
    bash
commands =
    make --directory docs clean
	make --directory docs {posargs:}
