---
# See https://nilearn.github.io/dev/ci.html for details.

version: 2.1

# Parameters required to trigger the execution of the "host_docs" job
parameters:
    GITHUB_RUN_URL:
        type: string
        default: none

workflows:
    wait:
        jobs:
        - wait-action
    host_and_deploy_doc:
        when:
            not:
                equal: [none, << pipeline.parameters.GITHUB_RUN_URL >>]
    # The jobs should run only when triggered by the workflow
        jobs:
        -   host_docs

    host_reports:
        jobs:
        - get-tests-reports

jobs:
    host_docs:
        machine:
            image: ubuntu-2204:current
        environment:
            GITHUB_ARTIFACT_URL: << pipeline.parameters.GITHUB_RUN_URL >>/doc.zip
        steps:
        -   checkout
        -   run:
                name: Download documentation
                command: bash tools/documentation/circleci/download_documentation.sh
        -   store_artifacts:
                path: docs/_build/html/
                destination: dev
        # Persists the generated documentation, so that it
        # can be attached and deployed in the "deploy" job
        -   persist_to_workspace:
                root: docs/_build
                paths:
                -   html

    get-tests-reports:
        docker:
        - image: cimg/base:2025.05
        environment:
        - GITHUB_ARTIFACT_URL: << pipeline.parameters.GITHUB_RUN_URL >>
        steps:
        - checkout
        - run:
            name: "get reports"
            command: |
                set -x -e
                wget $GITHUB_ARTIFACT_URL
                unzip pytest-results-all.zip -d test_reports
                mkdir -p docs/_build/html
                mv test_reports docs/_build/html
        # store the reports to display for a PR
        - store_artifacts:
            path: docs/_build/html/test_reports
            destination: documentation/test_reports
        # store the reports for adding them to the documentation
        - persist_to_workspace:
            root: docs/_build/html/
            paths: .

    # this action is only to avoid any error
    wait-action:
        docker:
        - image: cimg/base:2025.05
        steps:
        - run:
                name: "wait"
                command: sleep 10
