name: CircleCI artifacts redirector
on: [status]

# Restrict the permissions granted to the use of secrets.GITHUB_TOKEN in this
# github actions workflow:
# https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  statuses: write

jobs:
  circleci_documentation_redirection:
    runs-on: ubuntu-latest
    # For testing this action on a fork, remove the "github.repository =="" condition.
    if: "github.repository == 'mind-inria/hidimstat' && github.event.context == 'ci/circleci: build-documentation'"
    name: Run CircleCI artifacts redirector
    steps:
      - name: GitHub Action step
        uses: larsoner/circleci-artifacts-redirector-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          api-token: ${{ secrets.CIRCLE_CI }}
          artifact-path: 0/documentation/index.html
          circleci-jobs: build-documentation
          job-title: Check the rendered docs here!

  circleci_change_PR:
    runs-on: ubuntu-latest
    # For testing this action on a fork, remove the "github.repository =="" condition.
    if: "github.repository == 'mind-inria/hidimstat' && github.event.context == 'ci/circleci: build-documentation'"
    name: Run CircleCI artifacts redirector
    steps:
      - name: GitHub Action step
        uses: larsoner/circleci-artifacts-redirector-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          api-token: ${{ secrets.CIRCLE_CI }}
          artifact-path: 0/documentation/_changed.html
          circleci-jobs: build-documentation
          job-title: Check change in the PR!


